services:
  api1:
    build:
      context: ./api1_nest
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api1_nest:/app
    environment:
      NODE_ENV: development

  api2:
    build:
      context: ./api2_python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api2_python:/app
    environment:
      PYTHONUNBUFFERED: 1
