services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cervejas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api1:
    build:
      context: ./api1_nest
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api1_nest:/app
    environment:
      NODE_ENV: development
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: cervejas

  api2:
    build:
      context: ./api2_python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api2_python:/app
    environment:
      PYTHONUNBUFFERED: 1

volumes:
  postgres_data:
